### ISSUE TITLE
make `swap` automatically merge return value of `updateFn` with `state`

### ISSUE THREAD

**Issue by derrickbeining** [derrickbeining/react-atom#29]
It would be nice not to have to spread state all over the place in `swap`, like this:

```js
swap(atom, (state) => ({
  ...state,
  stuff: {
    ...state.stuff,
    things: [...state.stuff.things, newThing]
  }
})
```

and instead be able to do this:

```js
swap(atom, (state) => ({
  stuff: {
    things: [...state.stuff.things, newThing]
  }
})
```

`swap` would still work if you manually spread things like now, and we could avoid unnecessary deep merging by just checking `Object.is` between the old and new state and just skip merging those that are equal.

**Comment by nullberri** [comment]
You can already achieve this by combining React-Atom with Immer

```
import { Atom, swap } from "@dbeining/react-atom"
import produce from "immer"

const state = Atom.of({})
const createSetState = state => fn => swap(state, state => produce(state, fn))
const setState = createSetState(state)

setState(next => { /* do work here*/}
```
next is a copy of the current state, that you can modify next.property = data. When the function returns a new immutable object with your changes is created and swapped in with Atom. 
or you can return a new object to overwrite the current state.

**Comment by g770728y** [comment]
How could we ```delete``` a key from state when use ```updateFn``` ? @derrickbeining 
  
     swap(appState, s => {k: undefined})

right?

(BTW: I'm from clojurescript and reagent, I think the atom idea is great, pretty easy!!! Thank you so mach 👍 )

**Comment by Zzzen** [comment]
Please don't do it. It's already year 9102, all the cool kids are using immer.

**Comment by derrickbeining** [comment]
Closing this in favor of solutions like Immer and more functional approaches to updating nested structures (like lenses).
