### ISSUE TITLE
add to usehooks page

### ISSUE THREAD

**Issue by jsnelgro** [derrickbeining/react-atom#41]
Hey @derrickbeining, I've been playing around with your library and I really like the api! I think it should be added to the [usehooks](https://github.com/gragland/usehooks) page to increase its visibility.

**Comment by derrickbeining** [comment]
@jsnelgro that'd be cool! I'll look into it. If you have the bandwidth, feel free to submit it yourself and let me know.

**Comment by derrickbeining** [comment]
closing this as unactionable
