### ISSUE TITLE
Subscription list is invalidated if a parent unmounts a child.

### ISSUE THREAD

**Issue by nullberri** [derrickbeining/react-atom#44]
In the code below, k can be invalidated if a previous call to changeHandlersByAtomId causes a component to unmount farther down the list. 

```
function _runChangeHandlers(atom, previous, current) {
  Object.keys(changeHandlersByAtomId[atom["$$id"]]).forEach(function (k) {
    changeHandlersByAtomId[atom["$$id"]][k]({
      previous: previous,
      current: current
    });
  });
}
```

**Comment by derrickbeining** [comment]
Good find @nullberri. Could you give me a minimal example in codesandox.io that reproduces the issue? Happy to take a look.

**Comment by nullberri** [comment]
I wasn't able to reduce the complexity, without removing the error. So I am not sure what the underlying cause is. I was using react-window and have since just abandoned it for just pagination. Its not as good but virtualizating statefull components has been a pain. 

Just that what I was getting was an error that changeHandlersByAtomId[atom["$$id"]][k] was undefined.

**Comment by derrickbeining** [comment]
@nullberri gotcha. Well I'll keep an eye out for that bug. If I find some time, I'll try to find a way to reproduce it.

Am I good to close this, or is there anything else I can do?

**Comment by derrickbeining** [comment]
Closing. Feel free to reopen if you find a way to reproduce the issue.

**Comment by nullberri** [comment]
@derrickbeining  I figured it out.

Code to trigger the exception.
https://codesandbox.io/s/woo3z1n8kw

Should trigger 4x Uncaught TypeError: a[t.$$id][n] is not a function in the console.

**Comment by derrickbeining** [comment]
@nullberri thanks for a code sample! Unfortunately it's not reproducing on my end. Anything I should tinker with to trigger the issue?

**Comment by nullberri** [comment]
@derrickbeining  Strange it happens 100% of the time for me, even across multiple computers. (Work laptop, and home PC)

Chrome Version 72.0.3626.109 (Official Build) (64-bit) on Windows 10.

And the error only shows up in the inspector not the codsandbox.io console. 
I have included an image of the output I am seeing. 
https://i.imgur.com/MmkV6RL.png

**Comment by derrickbeining** [comment]
@nullberri ah! Wasn't looking in the browser console. Okay, awesome. I'll try to find some time to look into how to prevent this.

**Comment by derrickbeining** [comment]
@nullberri , just tested the fix out on code sandbox and it appears to resolve the issue.

Thanks for bringing it to my attention and helping find the solution!
